# Generated by Django 5.0.7 on 2024-07-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='', max_length=100, unique=True)),
                ('year_established', models.IntegerField(default=1)),
                ('location', models.CharField(default='', max_length=50)),
                ('gps_address', models.CharField(default='GD-212-8009', max_length=20)),
                ('headteacher', models.CharField(default='Chris', max_length=50)),
                ('facilitators', models.IntegerField(default=1)),
                ('learners', models.IntegerField(default=1)),
                ('core_subjects_pst', models.CharField(default='', max_length=5)),
                ('circuit_name', models.CharField(choices=[('Adjiringanor', 'Adjiringanor'), ('Adenta', 'Adenta'), ('Botwe', 'Botwe'), ('Nmai Dzorn', 'Nmai Dzorn')], default='Adjiringanor', max_length=20)),
                ('siso_name', models.CharField(choices=[('Florence Kushitor', 'Florence Kushitor'), ('Isaac Paintsil', 'Isaac Paintsil'), ('Joana Kumi', 'Joana Kumi'), ('Kingsley David', 'Kingsley David')], default='Florence Kushitor', max_length=50)),
                ('level', models.CharField(choices=[('BASIC', 'Basic'), ('JHS', 'JHS'), ('PRIMARY', 'Primary'), ('KG', 'Kingdergarten')], default='KG', max_length=15, verbose_name='School Level')),
                ('school_type', models.CharField(choices=[('Public', 'Public'), ('Public', 'Private')], default='Public', max_length=10, verbose_name='School Type')),
                ('isGALOP', models.BooleanField(verbose_name='Is Galop')),
            ],
        ),
    ]
