# Generated by Django 5.0.7 on 2024-07-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0002_circuit_info_remove_school_circuit_siso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='circuit_name',
            field=models.CharField(choices=[('Nmai Dzorn', 'Nmai Dzorn'), ('Adjiringanor', 'Adjiringanor'), ('Adenta', 'Adenta'), ('Botwe', 'Botwe')], default='Adjiringanor', max_length=20),
        ),
        migrations.RemoveField(
            model_name='siso',
            name='circuit_name',
        ),
        migrations.AlterField(
            model_name='school',
            name='siso_name',
            field=models.CharField(choices=[('Florence Kushitor', 'Florence Kushitor'), ('Isaac Paintsil', 'Isaac Paintsil'), ('Joana Kumi', 'Joana Kumi'), ('Kingsley David', 'Kingsley David')], default='Florence Kushitor', max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='level',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('JHS', 'JHS'), ('KG', 'Kingdergarten'), ('PRIMARY', 'Primary')], default='KG', max_length=15, verbose_name='School Level'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('Public', 'Private'), ('Public', 'Public')], default='Public', max_length=10, verbose_name='School Type'),
        ),
        migrations.DeleteModel(
            name='Circuit_INFO',
        ),
        migrations.DeleteModel(
            name='SISO',
        ),
    ]
