# Generated by Django 5.0.7 on 2024-07-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0002_alter_school_circuit_name_alter_school_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='isGALOP',
        ),
        migrations.AlterField(
            model_name='school',
            name='circuit_name',
            field=models.CharField(choices=[('Adjiringanor', 'Adjiringanor'), ('Nmai Dzorn', 'Nmai Dzorn'), ('Adenta', 'Adenta'), ('Botwe', 'Botwe')], default='Adjiringanor', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='level',
            field=models.CharField(choices=[('KG', 'Kindergarten'), ('PRIMARY', 'Primary'), ('JHS', 'JHS'), ('BASIC', 'Basic')], default='KG', max_length=15, verbose_name='School Level'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=10, verbose_name='School Type'),
        ),
        migrations.AddField(
            model_name='school',
            name='isGalop',
            field=models.BooleanField(default=False, verbose_name='Is Galop'),
        ),
    ]
