# Generated by Django 5.0.7 on 2024-07-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0003_remove_school_isgalop_alter_school_circuit_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='municipal-images/')),
            ],
        ),
    ]
