# Generated by Django 5.0.7 on 2024-07-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0003_alter_school_circuit_name_remove_siso_circuit_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='core_subjects_pst',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='school',
            name='facilitators',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='school',
            name='gps_address',
            field=models.CharField(default='GD-212-8009', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='headteacher',
            field=models.CharField(default='Chris', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='learners',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='year_established',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='school',
            name='circuit_name',
            field=models.CharField(choices=[('Botwe', 'Botwe'), ('Adjiringanor', 'Adjiringanor'), ('Adenta', 'Adenta'), ('Nmai Dzorn', 'Nmai Dzorn')], default='Adjiringanor', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='level',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('KG', 'Kingdergarten'), ('JHS', 'JHS'), ('BASIC', 'Basic')], default='KG', max_length=15, verbose_name='School Level'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
